"""baseline domain slice — identity, project spine and audit log

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-03

Creates the Fase 1 vertical slice in the ``portal`` schema (search_path pinned
by the engine): organization, user, project, membership, milestone, delivery,
pending_item and audit_log, plus their enum types.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('slug', name=op.f('uq_organization_slug'))
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('external_subject', name=op.f('uq_user_external_subject'))
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('discovery', 'in_implementation', 'live', 'paused', name='project_status'), nullable=False),
    sa.Column('completion_percent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completion_percent >= 0 AND completion_percent <= 100', name=op.f('ck_project_completion_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_project_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_project_organization_slug')
    )
    op.create_index(op.f('ix_project_organization_id'), 'project', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_log_actor_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_audit_log_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_audit_log_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_log_project_id'), 'audit_log', ['project_id'], unique=False)
    op.create_table('delivery',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'delivered', name='delivery_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_delivery_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_delivery_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery'))
    )
    op.create_index(op.f('ix_delivery_organization_id'), 'delivery', ['organization_id'], unique=False)
    op.create_index(op.f('ix_delivery_project_id'), 'delivery', ['project_id'], unique=False)
    op.create_table('membership',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('internal_admin', 'internal_member', 'client_member', name='member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_membership_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_membership_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_membership_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership')),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_membership_user_project')
    )
    op.create_index(op.f('ix_membership_organization_id'), 'membership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_membership_project_id'), 'membership', ['project_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('milestone',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('owner_label', sa.String(length=160), nullable=True),
    sa.Column('state', sa.Enum('planned', 'in_progress', 'next', 'done', name='milestone_state'), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_milestone_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_milestone_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_index(op.f('ix_milestone_organization_id'), 'milestone', ['organization_id'], unique=False)
    op.create_index(op.f('ix_milestone_project_id'), 'milestone', ['project_id'], unique=False)
    op.create_table('pending_item',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_label', sa.String(length=160), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='pending_priority'), nullable=False),
    sa.Column('state', sa.Enum('open', 'in_progress', 'resolved', name='pending_state'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_pending_item_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_pending_item_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_item'))
    )
    op.create_index(op.f('ix_pending_item_organization_id'), 'pending_item', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pending_item_project_id'), 'pending_item', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_item_project_id'), table_name='pending_item')
    op.drop_index(op.f('ix_pending_item_organization_id'), table_name='pending_item')
    op.drop_table('pending_item')
    op.drop_index(op.f('ix_milestone_project_id'), table_name='milestone')
    op.drop_index(op.f('ix_milestone_organization_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_project_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_organization_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_delivery_project_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_organization_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_audit_log_project_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_project_organization_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###
    # Enum types are not dropped by drop_table; remove them so a re-upgrade
    # does not fail with "type already exists".
    for enum_name in (
        'project_status',
        'member_role',
        'milestone_state',
        'delivery_status',
        'pending_priority',
        'pending_state',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
