"""knowledge and agent events

Revision ID: 0002_knowledge_and_events
Revises: 0001_baseline
Create Date: 2026-08-04

Adds the remaining Fase 1 data slice in the ``portal`` schema (search_path
pinned by the engine): document, meeting, decision and the idempotent
agent_event table, plus the ``document_source`` enum. Additive only — no
existing table is altered.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_knowledge_and_events'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event',
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('hours_saved', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_agent_event_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_agent_event_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_event')),
    sa.UniqueConstraint('project_id', 'external_event_id', name='uq_agent_event_external_event_id')
    )
    op.create_index(op.f('ix_agent_event_organization_id'), 'agent_event', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_event_project_id'), 'agent_event', ['project_id'], unique=False)
    op.create_table('document',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('upload', 'drive', 'transcript', name='document_source'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_document_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_document_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_organization_id'), 'document', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_project_id'), 'document', ['project_id'], unique=False)
    op.create_table('meeting',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_meeting_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_meeting_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting'))
    )
    op.create_index(op.f('ix_meeting_organization_id'), 'meeting', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meeting_project_id'), 'meeting', ['project_id'], unique=False)
    op.create_table('decision',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('owner_label', sa.String(length=160), nullable=True),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_decision_meeting_id_meeting'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_decision_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_decision_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    op.create_index(op.f('ix_decision_meeting_id'), 'decision', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_decision_organization_id'), 'decision', ['organization_id'], unique=False)
    op.create_index(op.f('ix_decision_project_id'), 'decision', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_project_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_organization_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_meeting_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_meeting_project_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_organization_id'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_document_project_id'), table_name='document')
    op.drop_index(op.f('ix_document_organization_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_agent_event_project_id'), table_name='agent_event')
    op.drop_index(op.f('ix_agent_event_organization_id'), table_name='agent_event')
    op.drop_table('agent_event')
    # ### end Alembic commands ###
    # Enum types are not dropped by drop_table; remove the one this revision
    # introduced so a re-upgrade does not fail with "type already exists".
    op.execute('DROP TYPE IF EXISTS document_source')
